apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      micro-svc: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - env:
        - name: SCRIPT_NAME
          value: /pgadmin4
        envFrom:
        - secretRef:
            name: pgadmin-config
        - configMapRef:
            name: pgadmin-files
        image: registry.il2.dso.mil/platform-one/devops/pipeline-templates/pgadmin4:latest
        name: pgadmin4
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 25m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 16Mi
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/pgadmin4
          name: empty-configdir
      imagePullSecrets:
      - name: code-il2-pull-creds
      initContainers:
      - args:
        - echo "create pgpass" set +x && echo ${PGHOST}:5432:${PG_DATABASE}:${PG_USER}:${APP_DB_ADMIN_PASSWORD}
          > /etc/pgadmin4/pgpass && set -x && echo "chown pgpass" && chown 5050:5050
          /etc/pgadmin4/pgpass && echo "chmod pgpass" && chmod 600 /etc/pgadmin4/pgpass
          && echo "substitute servers.json" && cp /pgadmin4/servers-template.json
          /etc/pgadmin4/servers.json && sed -i.bak "s|{{PG_USER}}|${PG_USER}|g" /etc/pgadmin4/servers.json
          && sed -i.bak "s|{{APP_NAME}}|${APP_NAME/-/_}|g" /etc/pgadmin4/servers.json
          && sed -i.bak "s|{{PG_HOST}}|${PGHOST}|g" /etc/pgadmin4/servers.json &&
          sed -i.bak "s|{{PG_DATABASE}}|${PG_DATABASE}|g" /etc/pgadmin4/servers.json
          && echo "chown servers.json" && chown 5050:5050 /etc/pgadmin4/servers.json
          && echo "chmod servers.json" && chmod 600 /etc/pgadmin4/servers.json
        command:
        - sh
        - -c
        envFrom:
        - secretRef:
            name: app-db-credentials
        - secretRef:
            name: postgres-connect-info
        - configMapRef:
            name: app-name
        image: registry.il2.dso.mil/platform-one/devops/pipeline-templates/busybox:1.32.0
        name: set-pgpass-owner
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /pgadmin4/servers-template.json
          name: postgresql-servers
          subPath: servers-template.json
        - mountPath: /etc/pgadmin4
          name: empty-configdir
      restartPolicy: Always
      volumes:
      - configMap:
          items:
          - key: servers-template.json
            path: servers-template.json
          name: pgadmin-servers
        name: postgresql-servers
      - emptyDir: {}
        name: empty-configdir
