apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  authentication: istio-auth
configMapGenerator:
  - name: sdi05-05-env
    literals:
      - APP_NAME=sdi05-05
resources:
  - ui/
  - api/
  - pgadmin/
